<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5cb0f4d80fb97256ba3e96c59abfa13d
{
    public static $prefixLengthsPsr4 = array (
        'J' =>
        array (
            'Jankx\\MembershipLevels\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Jankx\\MembershipLevels\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5cb0f4d80fb97256ba3e96c59abfa13d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5cb0f4d80fb97256ba3e96c59abfa13d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5cb0f4d80fb97256ba3e96c59abfa13d::$classMap;

        }, null, ClassLoader::class);
    }
}
